[package]
name = 'nftborrowlend'
version = '1.0.0'

[addresses]
borrowlend = "_"
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main',subdir = 'aptos-move/framework/aptos-framework' }
AptosToken = {  git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = "aptos-move/framework/aptos-token" }
AptosStdlib = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = "aptos-move/framework/aptos-stdlib" }

